/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geekerk_driptime_db_natived_JNIManager */

#ifndef _Included_com_geekerk_driptime_db_natived_JNIManager
#define _Included_com_geekerk_driptime_db_natived_JNIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geekerk_driptime_db_natived_JNIManager
 * Method:    getEmbededResult
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject
JNICALL Java_com_geekerk_driptime_db_natived_JNIManager_getEmbededResult
        (JNIEnv * , jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
